appform_frontend_homepage:
    path:     /
    defaults: { _controller: AppformFrontendBundle:Default:index }

appform_frontend_form:
    path:     /form
    defaults: { _controller: AppformFrontendBundle:Default:form }

appform_frontend_apply:
    path:     /apply
    defaults: { _controller: AppformFrontendBundle:Default:apply }
