frontend:
    resource: "@AppformFrontendBundle/Controller/DefaultController.php"
    type: "annotation"
    prefix: "/"

table:
    resource: "@AppformFrontendBundle/Controller/TableController.php"
    type: "annotation"
    prefix: "/"

contact:
    resource: "@AppformFrontendBundle/Controller/ContactController.php"
    type: "annotation"
    prefix: "/"