appform_frontend_homepage:
    path:     /
    defaults: { _controller: AppformFrontendBundle:Default:index }

appform_frontend_generate:
    path:     /generate
    defaults: { _controller: AppformFrontendBundle:Default:generate }

appform_frontend_renderform:
    path:     /getform
    defaults: { _controller: AppformFrontendBundle:Default:getform }

appform_frontend_getwidget:
    path:     /getwidget
    defaults: { _controller: AppformFrontendBundle:Default:getwidget }

appform_frontend_widgetdata:
    path:     /widgetdata
    defaults: { _controller: AppformFrontendBundle:Default:widget }