appform_frontend_homepage:
    path:     /
    defaults: { _controller: AppformFrontendBundle:Default:form }

appform_frontend_iframe:
    path:     /iframe
    defaults: { _controller: AppformFrontendBundle:Default:form }

appform_frontend_apply:
    path:     /apply
    defaults: { _controller: AppformFrontendBundle:Default:apply }
