appform_frontend_homepage:
    path:     /
    defaults: { _controller: AppformFrontendBundle:Default:index }

appform_frontend_iframe:
    path:     /iframe
    defaults: { _controller: AppformFrontendBundle:Default:iframe }

appform_frontend_widgetdata:
    path:     /widgetdata
    defaults: { _controller: AppformFrontendBundle:Default:widget }

