appform_frontend_homepage:
    path:     /
    defaults: { _controller: AppformFrontendBundle:Default:form }

appform_frontend_iframe:
    path:     /iframe
    defaults: { _controller: AppformFrontendBundle:Default:form }

appform_frontend_apply:
    path:     /apply
    defaults: { _controller: AppformFrontendBundle:Default:apply }

appform_frontend_success:
    path:     /success
    defaults: { _controller: AppformFrontendBundle:Default:success }

appform_frontend_table:
    path:     /table
    defaults: { _controller: AppformFrontendBundle:Table:index }

appform_frontend_info:
    path:     /info
    defaults: { _controller: AppformFrontendBundle:Content:index }