services:
    helper:
        class: Appform\FrontendBundle\Extensions\Helper
        arguments: [@doctrine.orm.entity_manager]
    counter:
        class: Appform\FrontendBundle\Extensions\Counter
        arguments: [@service_container, @doctrine.orm.entity_manager]
    firewall:
        class: Appform\FrontendBundle\Extensions\Firewall
        arguments: [@service_container, @doctrine.orm.entity_manager]