services:
    helper:
        class: Appform\FrontendBundle\Extensions\Helper
        arguments: [@doctrine.orm.entity_manager]

    appform_frontend.reporting:
        class: Appform\FrontendBundle\Reporting\Reporting
        arguments: ["@helper"]