Appform\FrontendBundle\Entity\Applicant:
    properties:
        firstName:
            - NotBlank:
                message: First Name field is empty.
            - Regex:
                pattern: "/[a-zA-Z10-9\*\s]+/"
                message: First Name field contains not allowed symbols
        lastName:
            - NotBlank:
                message: Last Name field is empty.
            - Regex:
                pattern: "/[a-zA-Z10-9\*\s]+/"
                message: Last Name field contains not allowed symbols
        email:
            - NotBlank:
                message: Email Address field is empty.
            - Email:
                message: Email Address {{ value }} is not correct.
                checkMX: true

Appform\FrontendBundle\Entity\PersonalInformation:
    properties:
        phone:
            - NotBlank:
                message: Phone Number field is empty.
            - Regex:
                pattern: "/^1+\(\d+\)[\d]+-[\d]+$/"
                message: "Phone Number field contains incorrect symbols"
        specialtyPrimary:
            - NotBlank:
                message: Specialty - Primary field is empty.
        state:
            - NotBlank:
                message: Home State field is empty.
        discipline:
            - NotBlank:
                message: Discipline / Professional License field is empty.
        licenseState:
            - NotBlank:
                message: Licensed State(s) field is empty.
        isExperiencedTraveler:
            - NotBlank:
                message: Are you an experienced Traveler? field is empty.
        assignementTime:
            - NotBlank:
                message: Assignment availability field is empty.
        yearsLicenceSp:
            - NotBlank:
                message: Primary specialty experience field is empty.
        desiredAssignementState:
            - NotBlank:
                message:  Assignment Location Preference field is empty.
        isOnAssignement:
            - NotBlank:
                message: On Assignment? field is empty.

Appform\FrontendBundle\Entity\Document:
    properties:
        file:
            - File:
                maxSize: 6000000
