Appform\FrontendBundle\Entity\Applicant:
    properties:
        firstName:
            - NotBlank:
                message: Name field is empty.
            - Regex:
                pattern: "/[a-zA-Z10-9\*\s]+/"
                message: Name field contains not allowed symbols
        middleName:
            - Regex:
                pattern: "/[a-zA-Z10-9\*\s]+/"
                message: Middle Name field contains not allowed symbols
        lastName:
            - NotBlank:
                message: Last Name field is empty.
            - Regex:
                pattern: "/[a-zA-Z10-9\*\s]+/"
                message: Last Name field contains not allowed symbols
        email:
            - NotBlank:
                message: Email field is empty.
            - Email:
                message: Email {{ value }} is formatted incorrectly.
                checkMX: true

Appform\FrontendBundle\Entity\PersonalInformation:
    properties:
        phone:
            - NotBlank:
                message: Phone field is empty.
            - Regex:
                pattern: "/^[\d\+\-\s\(\)]+$/"
                message: "Phone field contains not correct symbols"

        licenseState:
            - NotBlank:
                message: License State field is empty.
        desiredAssignementState:
            - NotBlank:
                message: Desired Asignement State field is empty.

Appform\FrontendBundle\Entity\Document:
    properties:
        file:
            - File:
                maxSize: 6000000
