Appform\FrontendBundle\Entity\Applicant:
    properties:
        firstName:
            - NotBlank:
                message: Name field is empty.
            - Regex:
                pattern: "/[a-zA-Z10-9\*\s]+/"
                message: Name field contains not allowed symbols
        email:
            - NotBlank:
                message: Почтовый адрес не заполнен.
            - Email:
                message: Почтовый адрес {{ value }} введен не корректно.
                checkMX: true

Appform\FrontendBundle\Entity\PersonalInformation:
