appform_frontend:
    resource: "@AppformFrontendBundle/Resources/config/routing.yml"
    prefix:   /

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /admin/profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /admin/register

fos_user_security_login:
    pattern:  /admin/login
    defaults: { _controller: FOSUserBundle:Security:login }

fos_user_security_check:
    pattern:  /admin/login_check
    defaults: { _controller: FOSUserBundle:Security:check }

fos_user_security_logout:
    pattern:  /admin/logout
    defaults: { _controller: FOSUserBundle:Security:logout }

appform_backend:
    resource: "@AppformBackendBundle/Resources/config/routing.yml"
    prefix:   /admin