<?php

namespace Appform\FrontendBundle\Entity;

/**
 * DisciplineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DisciplineRepository extends \Doctrine\ORM\EntityRepository
{
    public function getDisciplinesList($agency)
    {
        $disciplinesToHide = $this->getEntityManager()->getRepository('AppformBackendBundle:Rejection')->getDisciplinesHidePerVendor($agency);
        $idsToHide = array_column($disciplinesToHide, 'id');

        $qb = $this->createQueryBuilder('d')->select('d.id', 'd.name');
        if (!empty($idsToHide)) {
            $qb->where($qb->expr()->notIn('d.id', $idsToHide));
        }
        return $qb->orderBy('d.order', 'ASC')->getQuery()->getArrayResult();
    }
}
