<?php

namespace Appform\FrontendBundle\Entity;

/**
 * CounterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RedirectRepository extends \Doctrine\ORM\EntityRepository
{
	public function getDisciplineRedirect($disciplineId) {
		return $this->createQueryBuilder('r')
			->where('r.discipline = :disciplineId')
			->setParameter('disciplineId', $disciplineId)
            ->andWhere('r.specialty IS NULL')
			->getQuery()
			->getOneOrNullResult();
	}
}
