<?php

namespace Appform\FrontendBundle\Entity;
use Symfony\Component\Validator\Constraints\DateTime;

/**
 * VisitorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VisitorRepository extends \Doctrine\ORM\EntityRepository
{
	public function saveUniqueVisitor($ip, $referrer, $referrerUrl, $sitePage)
	{
		$lastActivity = new \DateTime('now');
		$em = $this->getEntityManager();

		if (!$this->hasVisitor($ip, $referrerUrl)) {
			$visitor = new Visitor();
			$visitor->setIp($ip);
			$visitor->setLastActivity($lastActivity);
			$visitor->setReferrer($referrer);
			$visitor->setReferrerUrl($referrerUrl);
			$visitor->setSitePage($sitePage);
			$em->persist($visitor);
			$em->flush();
		}
	}

	protected function hasVisitor($ip, $referrerUrl) {

		$time = new \DateTime('now');
		$time->modify('-1 day');

		return $this->createQueryBuilder('v')
				->select( 'count(v)' )
				->where('v.ip = :ip and v.referrerUrl = :referrerUrl')
				->andWhere('v.lastActivity > :time')
				->setParameter('ip', $ip)
				->setParameter('time', $time)
				->setParameter('referrerUrl', $referrerUrl)
				->getQuery()
				->getSingleScalarResult();
	}

}
