<?php

namespace Appform\FrontendBundle\Entity;

/**
 * VisitorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VisitorRepository extends \Doctrine\ORM\EntityRepository
{
	public function saveUniqueVisitor($ip, $referrer)
	{
		$lastActivity = new \DateTime('now');
		$em = $this->getEntityManager();

		if (!$this->hasVisitor($ip, $referrer)) {
			$visitor = new Visitor();
			$visitor->setIp($ip);
			$visitor->setLastActivity($lastActivity);
			$visitor->setReferrer($referrer);
			$em->persist($visitor);
			$em->flush();
		}
	}

	protected function hasVisitor($ip, $referrer) {

		return $this->createQueryBuilder('v')
				->select( 'count(v)' )
				->where('v.ip = :ip and v.referrer = :referrer')
				->setParameter('ip', $ip)
				->setParameter('referrer', $referrer)
				->getQuery()
				->getSingleScalarResult();
	}

}
