<?php

namespace Appform\BackendBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FilterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MailgroupRepository extends EntityRepository
{
    public function getGroupPerReferrer($referrer)
    {
        return $this->createQueryBuilder('m')
            ->where('m.originsList LIKE :origin')
            ->setParameter('origin', '%' . $referrer . '%')
            ->setMaxResults(1)
            ->getQuery()->getOneOrNullResult();

    }
}
