homepage:
    path:     /login
    defaults: { _controller: AppformBackendBundle:Default:index }

login_check:
  pattern:   /admin/login_check

logout:
  path: /admin/logout


backend:
    resource: "@AppformBackendBundle/Controller/DefaultController.php"
    type: "annotation"
    prefix: "/"

users:
    resource: "@AppformBackendBundle/Controller/UserController.php"
    type: "annotation"
    prefix: "/"


mailgroup:
    resource: "@AppformBackendBundle/Controller/MailgroupController.php"
    type: "annotation"
    prefix: "/"

agencygroup:
    resource: "@AppformBackendBundle/Controller/AgencyGroupController.php"
    type: "annotation"
    prefix: "/"

agency:
    resource: "@AppformBackendBundle/Controller/AgencyController.php"
    type: "annotation"
    prefix: "/"

campaign:
    resource: "@AppformBackendBundle/Controller/CampaignController.php"
    type: "annotation"
    prefix: "/"

crontask:
    resource: "@AppformBackendBundle/Controller/CronTaskController.php"
    type: "annotation"
    prefix: "/"

settings:
    resource: "@AppformBackendBundle/Controller/SettingsController.php"
    type: "annotation"
    prefix: "/"

stats_invoicing:
    resource: "@AppformBackendBundle/Controller/Stats/InvoicingController.php"
    type: "annotation"
    prefix: "/"