appform_backend_homepage:
    path:     /login
    defaults: { _controller: AppformBackendBundle:Default:index }

login_check:
  pattern:   /admin/login_check

logout:
  path: /admin/logout

appform_backend_index:
    path:     /index
    defaults: { _controller: AppformBackendBundle:Backend:index}

appform_backend_users:
    path:     /users
    defaults: { _controller: AppformBackendBundle:Backend:users }

appform_backend_user_edit:
    path:     /user/edit/{id}
    defaults: { _controller: AppformBackendBundle:Backend:userEdit }

appform_backend_user_delete:
    path:     /user/delete/{id}
    defaults: { _controller: AppformBackendBundle:Backend:userDelete }

appform_backend_file_download:
    path:     /file/download/{url}
    defaults: { _controller: AppformBackendBundle:Backend:downloadFile }

appform_backend_user_sendmessage:
    path:     /user/sendmessage/{id}
    defaults: { _controller: AppformBackendBundle:Backend:userSendMessage }
    options:
        expose: true

appform_backend_send_mess_to_users:
    path:     /send/users
    defaults: { _controller: AppformBackendBundle:Backend:sendMessage }
    options:
        expose: true
    methods: [POST]