appform_backend_homepage:
    path:     /login
    defaults: { _controller: AppformBackendBundle:Default:index }

login_check:
  pattern:   /admin/login_check

logout:
  path: /admin/logout

appform_backend_index:
    path:     /
    defaults: { _controller: AppformBackendBundle:Backend:index}
    options:
          expose: true

appform_backend_users:
    path:     /users
    defaults: { _controller: AppformBackendBundle:Backend:users }

appform_backend_user_edit:
    path:     /user/edit/{id}
    defaults: { _controller: AppformBackendBundle:Backend:userEdit }

appform_backend_user_delete:
    path:     /user/delete/{id}
    defaults: { _controller: AppformBackendBundle:Backend:userDelete }

appform_backend_file_download:
    path:     /file/download/{url}
    defaults: { _controller: AppformBackendBundle:Backend:downloadFile }
    requirements:

appform_backend_user_sendmessage:
    path:     /user/sendmessage/{id}
    defaults: { _controller: AppformBackendBundle:Backend:userSendMessage }
    options:
        expose: true

appform_backend_user_report:
    path:     /user/report
    defaults: { _controller: AppformBackendBundle:Backend:userReport }
    options:
        expose: true
    methods: [POST]

appform_backend_send_mess_to_users:
    path:     /send/users
    defaults: { _controller: AppformBackendBundle:Backend:sendMessage }
    options:
        expose: true
    methods: [POST]

appform_backend_regenerate:
    path:     /regenerate/users
    defaults: { _controller: AppformBackendBundle:Backend:regenerate }
    options:
        expose: true
    methods: [POST]

appform_backend_remove_users:
    path:     /remove/users
    defaults: { _controller: AppformBackendBundle:Backend:removeUsers }
    options:
        expose: true
    methods: [POST]


appform_backend_register_user:
    path:     /countof/register/users
    defaults: { _controller: AppformBackendBundle:Backend:getRegisterUsers}
    options:
          expose: true
    methods: [POST]

appform_backend_download:
    pattern:  /download/{filename}
    defaults: { _controller: AppformBackendBundle:Backend:download }
    requirements:
        filename: .+

appform_backend_fix:
    pattern:  /fix
    defaults: { _controller: AppformBackendBundle:Backend:fix }
