homepage:
    path:     /login
    defaults: { _controller: AppformBackendBundle:Default:index }

login_check:
  pattern:   /admin/login_check

logout:
  path: /admin/logout


backend:
    resource: "@AppformBackendBundle/Controller/DefaultController.php"
    type: "annotation"
    prefix: "/"

users:
    resource: "@AppformBackendBundle/Controller/UserController.php"
    type: "annotation"
    prefix: "/"


mailgroup:
    resource: "@AppformBackendBundle/Controller/MailgroupController.php"
    type: "annotation"
    prefix: "/"

agencygroup:
    resource: "@AppformBackendBundle/Controller/AgencyGroupController.php"
    type: "annotation"
    prefix: "/"

agency:
    resource: "@AppformBackendBundle/Controller/AgencyController.php"
    type: "annotation"
    prefix: "/"

campaign:
    resource: "@AppformBackendBundle/Controller/CampaignController.php"
    type: "annotation"
    prefix: "/"

crontask:
    resource: "@AppformBackendBundle/Controller/CronTaskController.php"
    type: "annotation"
    prefix: "/"

settings:
    resource: "@AppformBackendBundle/Controller/SettingsController.php"
    type: "annotation"
    prefix: "/"

user_edit:
    path:     /user/edit/{id}
    defaults: { _controller: AppformBackendBundle:Backend:userEdit }

user_delete:
    path:     /user/delete/{id}
    defaults: { _controller: AppformBackendBundle:Backend:userDelete }

file_download:
    path:     /file/download/{url}
    defaults: { _controller: AppformBackendBundle:Backend:downloadFile }
    requirements:

user_sendmessage:
    path:     /user/sendmessage/{id}
    defaults: { _controller: AppformBackendBundle:Backend:userSendMessage }
    options:
        expose: true

user_report:
    path:     /user/report
    defaults: { _controller: AppformBackendBundle:Backend:userReport }
    options:
        expose: true
    methods: [POST]

send_mess_to_users:
    path:     /send/users
    defaults: { _controller: AppformBackendBundle:Backend:sendMessage }
    options:
        expose: true
    methods: [POST]

regenerate:
    path:     /regenerate/users
    defaults: { _controller: AppformBackendBundle:Backend:regenerate }
    options:
        expose: true
    methods: [POST]

remove_users:
    path:     /remove/users
    defaults: { _controller: AppformBackendBundle:Backend:removeUsers }
    options:
        expose: true
    methods: [POST]


register_user:
    path:     /countof/register/users
    defaults: { _controller: AppformBackendBundle:Backend:getRegisterUsers}
    options:
          expose: true
    methods: [POST]

download:
    pattern:  /download/{filename}
    defaults: { _controller: AppformBackendBundle:Backend:download }
    requirements:
        filename: .+

fix:
    pattern:  /fix
    defaults: { _controller: AppformBackendBundle:Backend:fix }

save_filter:
    path:     /savefilter
    defaults: { _controller: AppformBackendBundle:Backend:saveFilter }
    options:
        expose: true
    methods: [POST]